[package]
name = "backend"
version = "0.1.0"
authors = ["Stephen F <snipeydev@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.9"
actix-files = "0.1.7"
actix-multipart = "0.1.5"
tokio-timer = "0.2.12"

core = { path = "../core" }
