[package]
name = "odin-local-provider"
version = "0.1.0"
authors = ["snipey"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
